'use client'

import React, { useState, useEffect } from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ParentComponentProperties } from './types'
import { NextUIProvider } from "@nextui-org/react";
import { Suspense } from 'react';
import Nav from '@/components/navBar/navbar'
import { useIndicators } from '@/lib/hooks/useIndicatorData'
import { useMarkets } from '@/lib/hooks/useMarketData'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(properties: ParentComponentProperties) {
  const [loading, setLoading] = useState(true);
  const indicators = useIndicators();
  const markets = useMarkets();

  useEffect(() => {
    const indicatorSetup = indicators.refresh().then(result => {
      indicators.select(result[0])
    });

    const marketSetup = markets.refresh().then(result => {
      markets.select(result[0])
    });

    Promise.all([indicatorSetup, marketSetup]).then(x => {
      console.log(markets.current())
      setLoading(false)
    })

  }, []);

  return (
    <html lang="en" className=''>
      <body className={`sm:overflow-hidden overflow-y-auto ${inter.className}`}>
        <NextUIProvider>
          <main className="min-h-screen">
            {
              loading ? (
                <>Loading</>
              ) :
                (<div className='w-full min-h-screen'>
                  <Nav>
                    <Suspense fallback={<div>Loading...</div>}>
                    </Suspense>
                  </Nav>
                  <div className='w-full min-h-screen sm:pl-60 bg-stone-200 dark:bg-stone-900'>
                    <div className='w-full h-full transition-transform'>
                      {properties.children}
                    </div>
                  </div>
                </div>)
            }
          </main>
        </NextUIProvider>
      </body>
    </html>
  )
}
